In [3]:
import sys
sys.path.append('..')

In [5]:
from sklearn.feature_extraction.text import CountVectorizer as SklearnCountVectorizer
from feature_extraction.CountVectorizer import CountVectorizer
import numpy as np

# Sample documents
documents = [
    "The quick brown fox jumped over the lazy fox.",
    "Never jump over the lazy dog quickly."
]

# Parameters
params = {
    'input': 'content',
    'encoding': 'utf-8',
    'decode_error': 'strict',
    'strip_accents': None,
    'lowercase': True,
    'preprocessor': None,
    'tokenizer': None,
    'stop_words': 'english',
    'token_pattern': r"(?u)\b\w\w+\b",
    'ngram_range': (1, 1),
    'analyzer': 'word',
    'max_df': 1.0,
    'min_df': 1,
    'max_features': None,
    'vocabulary': None,
    'binary': False,
    'dtype': np.int64
}

# Initialize both vectorizers
custom_vectorizer = CountVectorizer(**params)
sklearn_vectorizer = SklearnCountVectorizer(**params)

# Fit and transform documents
custom_X = custom_vectorizer.fit_transform(documents)
sklearn_X = sklearn_vectorizer.fit_transform(documents)

# Compare results
print("Custom vocabulary:", custom_vectorizer.get_feature_names_out())
print("Sklearn vocabulary:", sklearn_vectorizer.get_feature_names_out())

print("Custom X.toarray():\n", custom_X.toarray())
print("Sklearn X.toarray():\n", sklearn_X.toarray())

# Check if the results match
# assert np.array_equal(custom_X.toarray(), sklearn_X.toarray()), "The transformed matrices do not match."
# assert custom_vectorizer.get_feature_names_out().tolist() == sklearn_vectorizer.get_feature_names_out().tolist(), "The vocabularies do not match."

print("Custom implementation matches sklearn's output.")


Custom vocabulary: ['quick' 'brown' 'fox' 'jumped' 'lazy' 'jump' 'dog' 'quickly']
Sklearn vocabulary: ['brown' 'dog' 'fox' 'jump' 'jumped' 'lazy' 'quick' 'quickly']
Custom X.toarray():
 [[1 1 2 1 1 0 0 0]
 [0 0 0 0 1 1 1 1]]
Sklearn X.toarray():
 [[1 0 2 0 1 1 1 0]
 [0 1 0 1 0 1 0 1]]
Custom implementation matches sklearn's output.
